version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      # These will be overridden by .env.local during development
      - PROWLARR_URL
      - PROWLARR_API_KEY
      - TMDB_API_KEY
      - RADARR_URL
      - RADARR_API_KEY
      - SONARR_URL
      - SONARR_API_KEY
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run dev
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
