version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

      - PROWLARR_URL=${PROWLARR_URL:-http://prowlarr:9696}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY:-your-prowlarr-api-key}
      - TMDB_API_KEY=${TMDB_API_KEY:-your-tmdb-api-key}

      - RADARR_URL=${RADARR_URL:-}
      - RADARR_API_KEY=${RADARR_API_KEY:-}
      - SONARR_URL=${SONARR_URL:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}
    
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "node", "scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo-data:
