version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      
      # Redis configuration
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your-redis-password}
      
      # API credentials - these should be set in a .env file
      - PROWLARR_URL=${PROWLARR_URL:-http://prowlarr:9696}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY:-your-prowlarr-api-key}
      - TMDB_API_KEY=${TMDB_API_KEY:-your-tmdb-api-key}
      
      # Other API credentials (optional)
      - RADARR_URL=${RADARR_URL:-}
      - RADARR_API_KEY=${RADARR_API_KEY:-}
      - SONARR_URL=${SONARR_URL:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}
    
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-your-redis-password}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
