version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      # API credentials with explicit values
      - PROWLARR_URL=http://192.168.1.62:9696
      - PROWLARR_API_KEY=c3cbb350fea74bf693fa117e10e28613
      - TMDB_API_KEY=2a64ce7c85da2b1542930819517136ea
      # Public versions for client-side access
      - NEXT_PUBLIC_PROWLARR_URL=http://192.168.1.62:9696
      - NEXT_PUBLIC_PROWLARR_API_KEY=c3cbb350fea74bf693fa117e10e28613
      - NEXT_PUBLIC_TMDB_API_KEY=2a64ce7c85da2b1542930819517136ea
      # Other API credentials
      - RADARR_URL
      - RADARR_API_KEY
      - SONARR_URL
      - SONARR_API_KEY
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run dev
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
